# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
  
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

fib <- c(1, 2, 3, 5, 8, 13, 21, 34, 55, 89)
repeat {
  f_n <- sum(tail(fib,2));  
  
  if (f_n >4e6) { break }
  
  fib <- append(fib,f_n)
}
sum(fib[fib%%2 == 0])


# There are a lot of ways outside to calculate fibonacci series
# The standard recursive definition is too slow without caching/memoization,
# that isn't built in by default to R.
# I think my solution is pretty much a 1:1 translation of the problem text,
# but not the most efficient.
# That would be a direct access to the array, but this hides what we do behind how we do it.